sudo: false
language: go
go_import_path: go.uber.org/thriftrw

env:
  global:
    - GO111MODULE=on

matrix:
  include:
  - go: 1.12.x
  - go: 1.13.x
    env: LINT=1

# Download modules and install tools.
install:
  - go mod download
  - make tools

script:
  - test -z "$LINT" || make lint
  - make test

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
